// js/data.js

const batteryData = [
  {
    id: "1",
    model: "A 55L",
    plates: 7,
    ah: 32,
    p: 12,
    warranty: "6 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/automotive/a55.png",
    categories: ["Automotive"], // Fixed filters
    uses: "Small Hatchbacks, Generators",
  },
  {
    id: "2",
    model: "A 60L",
    plates: 9,
    ah: 42,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/automotive/a60.png",
    categories: ["Automotive"],
    uses: "Small Hatchbacks, Generators",
  },
  {
    id: "3",
    model: "A 65L",
    plates: 11,
    ah: 50,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/automotive/a65.png",
    categories: ["Automotive"],
    uses: "Small Hatchbacks, Generators",
  },
  {
    id: "4",
    model: "A 70L",
    plates: 11,
    ah: 50,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/automotive/a70.png",
    categories: ["Automotive"],
    uses: "Small Hatchbacks, Generators",
  },
  {
    id: "5",
    model: "A 75L",
    plates: 13,
    ah: 55,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/automotive/a75.png",
    categories: ["Automotive"],
    uses: "Small Hatchbacks, Generators",
  },
  {
    id: "6",
    model: "A 90",
    plates: 9,
    ah: 50,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/automotive/a90.png",
    categories: ["Automotive"],
    uses: "Small Hatchbacks, Generators",
  },
  {
    id: "7",
    model: "A 95Z",
    plates: 11,
    ah: 60,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/automotive/a95.png",
    categories: ["Automotive"],
    uses: "Small Hatchbacks, Generators",
  },
  {
    id: "8",
    model: "A 110",
    plates: 11,
    ah: 70,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/automotive/a110.png",
    categories: ["Automotive"],
    uses: "Small Hatchbacks, Generators",
  },
  {
    id: "9",
    model: "A 115",
    plates: 13,
    ah: 80,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/automotive/a115.png",
    categories: ["Automotive", "Solar"],
    uses: "Generators, Solar Inverters",
  },
  {
    id: "10",
    model: "A 120Z",
    plates: 15,
    ah: 85,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/automotive/a120.png",
    categories: ["Automotive", "Solar"],
    uses: "Generators, Solar Inverters",
  },
  {
    id: "11",
    model: "Solar-50",
    plates: 5,
    ah: 50,
    p: 12,
    warranty: "6 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/solar/s50.png",
    categories: ["Solar"],
    uses: "Home UPS, Solar Inverters",
  },
  {
    id: "12",
    model: "Solar-100",
    plates: 9,
    ah: 60,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/solar/s100.png",
    categories: ["Solar"],
    uses: "Home UPS, Solar Inverters,Off-Grid Home Systems",
  },
  {
    id: "13",
    model: "A 130",
    plates: 15,
    ah: 100,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/solar/s130.png",
    categories: ["Solar"],
    uses: "Home UPS, Solar Inverters,Off-Grid Home Systems",
  },
  {
    id: "14",
    model: "A 140",
    plates: 17,
    ah: 105,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/solar/s140.png",
    categories: ["Solar"],
    uses: "Home UPS, Solar Inverters,Off-Grid Home Systems",
  },
  {
    id: "15",
    model: "A 150",
    plates: 17,
    ah: 110,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/solar/s150.png",
    categories: ["Solar", "Industrial"],
    uses: "Home UPS, Solar Inverters,Agricultural Machinery",
  },
  {
    id: "16",
    model: "A 160",
    plates: 19,
    ah: 115,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/solar/s160.png",
    categories: ["Solar", "Industrial"],
    uses: "Home UPS, Solar Inverters,Agricultural Machinery",
  },
  {
    id: "17",
    model: "A 180",
    plates: 19,
    ah: 120,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/industrial/a180.png",
    categories: ["Industrial"],
    uses: "Agricultural Machinery, Heavy Vehicles,Heavy Machinery Backup",
  },
  {
    id: "18",
    model: "A 200",
    plates: 21,
    ah: 130,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/industrial/a200.png",
    categories: ["Industrial"],
    uses: "Agricultural Machinery, Heavy Vehicles,Heavy Machinery Backup",
  },
  {
    id: "19",
    model: "A 210",
    plates: 21,
    ah: 135,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/industrial/a210.png",
    categories: ["Industrial"],
    uses: "Agricultural Machinery, Heavy Vehicles,Heavy Machinery Backup",
  },
  {
    id: "20",
    model: "A 230",
    plates: 23,
    ah: 150,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/industrial/a230.png",
    categories: ["Industrial"],
    uses: "Agricultural Machinery, Heavy Vehicles,Heavy Machinery Backup",
  },
  {
    id: "21",
    model: "A 260",
    plates: 25,
    ah: 160,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/industrial/a260.png",
    categories: ["Industrial"],
    uses: "Agricultural Machinery, Heavy Vehicles,Heavy Machinery Backup",
  },
  {
    id: "22",
    model: "A 270",
    plates: 27,
    ah: 180,
    p: 12,
    warranty: "9 Months",
    tech: "Graphite Enhanced Lead-Acid Battery",
    image: "assets/batteries/industrial/a270.png",
    categories: ["Industrial"],
    uses: "Agricultural Machinery, Heavy Vehicles,Heavy Machinery Backup",
  },
];

// Helper function to get products by series
const getProductsBySeries = (seriesName) => {
  return batteryData.filter((item) => item.series === seriesName);
};
