// This would ideally live in js/data.js
const dealers = [
  {
    name: "Abdullah Traders - Jhang",
    address: "Sargodha Road, Madni Colony, Jhang Sadar, Jhang",
    city: "Jhang",
    province: "PUNJAB",
    contact: "0300-0065094",
  },
  {
    name: "Ahsan Battery Solar & UPS Service Centre - More Khunda",
    address: "Mirza Haroon Battery Service UPS & Solar Jaranwala Road More Khunda",
    city: "More Khunda",
    province: "PUNJAB",
    contact: "0301-4192819/0300-4902995",
  },
  {
    name: "Al Karam Auto Store - Mandi Bahauddin",
    address: "Larri Adda, Mandi Bahauddin",
    city: "Mandi Bahauddin",
    province: "PUNJAB",
    contact: "0340-4898273",
  },
  {
    name: "Asif Battery Point - Phalia",
    address: "Gang Baksh Auto & Battery Centre, Qanchi Chowk, Opp Sheikh Hotel, Mandi Road, Phalia",
    city: "Phalia",
    province: "PUNJAB",
    contact: "0345-5794000/0321-7748767",
  },
  {
    name: "Baoo Jee Enterprises - Faisalabad",
    address: "Shop#77, Shoaib Bilal Market, Opp Mian Trust Market, Faisalabad",
    city: "Faisalabad",
    province: "PUNJAB",
    contact: "0324-6697095",
  },
  {
    name: "Bilal Battery Center - Garh More",
    address: "Multan Road, Garh More",
    city: "Garh More",
    province: "PUNJAB",
    contact: "0300-4029561",
  },
  {
    name: "Bismillah Battery & Solar System - Faisalabad",
    address: "P-45, Bilal Market, Jhang Road, Faisalabad",
    city: "Faisalabad",
    province: "PUNJAB",
    contact: "0300-7613563/0321-7613563",
  },
  {
    name: "Faisal Battery Service - Chiniot",
    address: "Main Sargodha Road, Chiniot",
    city: "Chiniot",
    province: "PUNJAB",
    contact: "0345-7763784",
  },
  {
    name: "Ghousia Battery Center - Shorkot",
    address: "Sultan Bahoo Road, Shorkot City",
    city: "Shorkot",
    province: "PUNJAB",
    contact: "0300-6500589",
  },
  {
    name: "Hafiz Auto & Battery - Faisalabad",
    address: "Shop#44, Jhal Khanuana, Faisalabad",
    city: "Faisalabad",
    province: "PUNJAB",
    contact: "0300-7212450/0321-7212450",
  },
  {
    name: "Hanan Auto & Battery Centre - Kamalia",
    address: "Zeeshan Shaheed Road, Kamalia",
    city: "Kamalia",
    province: "PUNJAB",
    contact: "0333-6884639",
  },
  {
    name: "Haq Bahu Battery & Solar Service - Jhang",
    address: "Church Road, Near General Bus Stand, Jhang Sadar",
    city: "Jhang",
    province: "PUNJAB",
    contact: "0300-6503945/0345-7975389",
  },
  {
    name: "Haseeb Battery Service - Kamalia",
    address: "Katcheri Bazar, Kamalia",
    city: "Kamalia",
    province: "PUNJAB",
    contact: "0301-7264770",
  },
  {
    name: "Hassan Autos - Faisalabad",
    address: "Shop#17,18, Shoaib Bilal Market, Faisalabad",
    city: "Faisalabad",
    province: "PUNJAB",
    contact: "0321-6652435",
  },
  {
    name: "Irfan Battery Service - Faisalabad",
    address: "Sitara Colony Road, Sammundri Road, Faisalabad",
    city: "Faisalabad",
    province: "PUNJAB",
    contact: "0300-6644131",
  },
  {
    name: "Khurram Battery Center - Gojra",
    address: "Main Jhang Road, Gojra",
    city: "Gojra",
    province: "PUNJAB",
    contact: "0300-6635293",
  },
  {
    name: "Madina Battery & Solar System - Faisalabad",
    address: "Gole Chowk, Aminabad, Faisalabad",
    city: "Faisalabad",
    province: "PUNJAB",
    contact: "0300-6627681",
  },
  {
    name: "Madina Battery Solar Center - Sangla Hill",
    address: "Safaida Road, Sangla Hill",
    city: "Sangla Hill",
    province: "PUNJAB",
    contact: "0300-4340762",
  },
  {
    name: "Masha Allah Autos & Battery - Pirmahal",
    address: "Pirmahal, Kamalia Road, Pirmahal",
    city: "Pirmahal",
    province: "PUNJAB",
    contact: "0333-6887550/0345-7798750",
  },
  {
    name: "Mian Battery Centre - Jaranwala",
    address: "Bypass Road, Opposite Sitara Mill, Jaranwala",
    city: "Jaranwala",
    province: "PUNJAB",
    contact: "0321-6651231",
  },
  {
    name: "New Chaudhry Battery & Solar Centre - Faisalabad",
    address: "P-43, Opp Utility Store, Jhang Road, Faisalabad",
    city: "Faisalabad",
    province: "PUNJAB",
    contact: "0321-6600985",
  },
  {
    name: "Pak Auto Electric Works & Battery Service - Tandlianwala",
    address: "Zafar Chowk, Tandlianwala",
    city: "Tandlianwala",
    province: "PUNJAB",
    contact: "0300-7212879",
  },
  {
    name: "Pasha Battery Centre - Faisalabad",
    address: "Plot#334-D, Ground Floor, Chiniot Bazar, Faisalabad",
    city: "Faisalabad",
    province: "PUNJAB",
    contact: "0321-8664445",
  },
  {
    name: "Rajput Battery & Solar System - Chiniot",
    address: "Bismillah Chowk, Chiniot",
    city: "Chiniot",
    province: "PUNJAB",
    contact: "0345-7711223",
  },
  {
    name: "Rana Battery Service - Summundri",
    address: "Rajana Road, Opp Police Station, Summundri",
    city: "Summundri",
    province: "PUNJAB",
    contact: "0300-6663240",
  },
  {
    name: "Rana Solar & Battery Center - Chak Jhumra",
    address: "Rail Bazar, Chak Jhumra",
    city: "Chak Jhumra",
    province: "PUNJAB",
    contact: "0300-6677947",
  },
  {
    name: "Sami Battery Solar Center - Toba Tek Singh",
    address: "Jhang Road, Toba Tek Singh",
    city: "Toba Tek Singh",
    province: "PUNJAB",
    contact: "0333-4017631",
  },
  {
    name: "Sardar Solar & Battery Centre - Shahkot",
    address: "Nankana Road, Opp Civil Hospital, Shahkot",
    city: "Shahkot",
    province: "PUNJAB",
    contact: "0300-8438127",
  },
  {
    name: "Shahid Battery & Solar Service - Jhang",
    address: "Shop#8, Yousaf Shah Road, Jhang",
    city: "Jhang",
    province: "PUNJAB",
    contact: "0300-6500192",
  },
  {
    name: "Siddique Battery Center - Dijkot",
    address: "Shop#6, Main Bazar, Dijkot",
    city: "Dijkot",
    province: "PUNJAB",
    contact: "0345-7762635",
  },
  {
    name: "Standard Battery Centre - Faisalabad",
    address: "10-B, Main Sargodha Road, Faisalabad",
    city: "Faisalabad",
    province: "PUNJAB",
    contact: "0300-8662916",
  },
  {
    name: "Sultan Battery Service - Sargodha",
    address: "Kutchery Road, Sargodha",
    city: "Sargodha",
    province: "PUNJAB",
    contact: "0300-9602494",
  },
  {
    name: "Super Battery Center - Sargodha",
    address: "Faisalabad Road, Sargodha",
    city: "Sargodha",
    province: "PUNJAB",
    contact: "0300-6047721",
  },
  {
    name: "Usman Battery House - Nankana Sahib",
    address: "Shah Kot Road, Nankana Sahib",
    city: "Nankana Sahib",
    province: "PUNJAB",
    contact: "0300-4131584",
  },
  {
    name: "Zain Solar & Battery - Shahpur",
    address: "Main Khushab Road, Shahpur City",
    city: "Shahpur",
    province: "PUNJAB",
    contact: "0300-6003294",
  },
  {
    name: "Hafiz Battery Service - Bhalwal",
    address: "Sargodha Road, Bhalwal",
    city: "Bhalwal",
    province: "PUNJAB",
    contact: "0344-4601956",
  },
  {
    name: "Subhan Battery & Solar - Kot Momin",
    address: "Sargodha Road, Kot Momin",
    city: "Kot Momin",
    province: "PUNJAB",
    contact: "0300-4740030",
  },
  {
    name: "Irfan Battery House - Silanwali",
    address: "Sargodha Road, Silanwali",
    city: "Silanwali",
    province: "PUNJAB",
    contact: "0300-6031756",
  },
  {
    name: "Malik Battery Solar Service - Joharabad",
    address: "Chowk Munara, Joharabad",
    city: "Joharabad",
    province: "PUNJAB",
    contact: "0300-6091316",
  },
  {
    name: "Awais Battery Centre - Mianwali",
    address: "Bannu Road, Mianwali",
    city: "Mianwali",
    province: "PUNJAB",
    contact: "0333-6842517",
  },
  {
    name: "Friends Battery & Solar Center - Bhakkar",
    address: "Darya Khan Road, Bhakkar",
    city: "Bhakkar",
    province: "PUNJAB",
    contact: "0333-6851451",
  },
  {
    name: "Gulzar Battery Service - Darya Khan",
    address: "Mianwali Road, Darya Khan",
    city: "Darya Khan",
    province: "PUNJAB",
    contact: "0333-6846152",
  },
  {
    name: "Zahid Battery House - Kallur Kot",
    address: "Main Bazar, Kallur Kot",
    city: "Kallur Kot",
    province: "PUNJAB",
    contact: "0300-6085526",
  },
  {
    name: "Hassan Battery Solar Center - Mankera",
    address: "Bhakkar Road, Mankera",
    city: "Mankera",
    province: "PUNJAB",
    contact: "0345-8730415",
  },
  {
    name: "Ali Battery & Solar - Hyderabad",
    address: "Main Auto Bhan Road, Unit No. 3 Latifabad, Hyderabad",
    city: "Hyderabad",
    province: "SINDH",
    contact: "0300-3011354",
  },
  {
    name: "Awan Battery Service - Hyderabad",
    address: "Shop # 1,2 Prince Ali Road, Hyderabad",
    city: "Hyderabad",
    province: "SINDH",
    contact: "0300-3014902",
  },
  {
    name: "Bismillah Battery & Solar - Mirpurkhas",
    address: "Umerkot Road, Mirpurkhas",
    city: "Mirpurkhas",
    province: "SINDH",
    contact: "0333-2971233",
  },
  {
    name: "Evershine Battery Service - Hyderabad",
    address: "Shop # 5,6,7 Al-Rahim Shopping Center, Near Makkah Hotel, Hyderabad",
    city: "Hyderabad",
    province: "SINDH",
    contact: "0300-9372297",
  },
  {
    name: "Ghaffar Battery Service - Tando Allahyar",
    address: "Mirpurkhas Road, Tando Allahyar",
    city: "Tando Allahyar",
    province: "SINDH",
    contact: "0333-2720275",
  },
  {
    name: "Ishaq Battery Service - Sanghar",
    address: "Nawabshah Road, Sanghar",
    city: "Sanghar",
    province: "SINDH",
    contact: "0333-2850388",
  },
  {
    name: "Javed Battery Center - Matli",
    address: "Tando Ghulam Ali Road, Matli",
    city: "Matli",
    province: "SINDH",
    contact: "0300-3051421",
  },
  {
    name: "Karachi Battery Service - Hyderabad",
    address: "Shop # 11, Haji Sultan Market, Hala Naka, Hyderabad",
    city: "Hyderabad",
    province: "SINDH",
    contact: "0333-2612765",
  },
  {
    name: "MashaAllah Battery Service - Tando Adam",
    address: "Hyderabad Road, Tando Adam",
    city: "Tando Adam",
    province: "SINDH",
    contact: "0333-2864669",
  },
  {
    name: "Mehran Battery House - Badin",
    address: "Hyderabad Road, Badin",
    city: "Badin",
    province: "SINDH",
    contact: "0300-3331448",
  },
  {
    name: "Memom Battery Solar - Shahdadpur",
    address: "Hala Road, Shahdadpur",
    city: "Shahdadpur",
    province: "SINDH",
    contact: "0333-2872332",
  },
  {
    name: "National Battery & UPS Center - Hyderabad",
    address: "Shop # 9,10, Block D, Unit # 7 Latifabad, Hyderabad",
    city: "Hyderabad",
    province: "SINDH",
    contact: "0333-2603415",
  },
  {
    name: "New Rajput Battery Service - Nawabshah",
    address: "Sanghar Road, Nawabshah",
    city: "Nawabshah",
    province: "SINDH",
    contact: "0300-3211516",
  },
  {
    name: "Pakistan Battery House - Hyderabad",
    address: "Shop # 4, Haji Sultan Market, Hala Naka, Hyderabad",
    city: "Hyderabad",
    province: "SINDH",
    contact: "0300-3013897",
  },
  {
    name: "Popular Battery Center - Hyderabad",
    address: "Shop # 8, Haji Sultan Market, Hala Naka, Hyderabad",
    city: "Hyderabad",
    province: "SINDH",
    contact: "0333-2612502",
  },
  {
    name: "Qureshi Battery & Solar - Mirpurkhas",
    address: "Hyderabad Road, Mirpurkhas",
    city: "Mirpurkhas",
    province: "SINDH",
    contact: "0333-2965313",
  },
  {
    name: "Rajput Battery Service - Nawabshah",
    address: "Sanghar Road, Nawabshah",
    city: "Nawabshah",
    province: "SINDH",
    contact: "0333-2821516",
  },
  {
    name: "Rehman Battery Service - Hyderabad",
    address: "Shop # 7, Haji Sultan Market, Hala Naka, Hyderabad",
    city: "Hyderabad",
    province: "SINDH",
    contact: "0333-2614531",
  },
  {
    name: "Sachal Battery & Solar - Umerkot",
    address: "Mirpurkhas Road, Umerkot",
    city: "Umerkot",
    province: "SINDH",
    contact: "0333-2838383",
  },
  {
    name: "Saima Battery Service - Hyderabad",
    address: "Shop # 15, Haji Sultan Market, Hala Naka, Hyderabad",
    city: "Hyderabad",
    province: "SINDH",
    contact: "0333-2605334",
  },
  {
    name: "Shahbaz Battery Center - Hyderabad",
    address: "Shop # 12, Haji Sultan Market, Hala Naka, Hyderabad",
    city: "Hyderabad",
    province: "SINDH",
    contact: "0333-2616421",
  },
  {
    name: "Sindh Battery & Solar - Hyderabad",
    address: "Shop # 1,2 Haji Sultan Market, Hala Naka, Hyderabad",
    city: "Hyderabad",
    province: "SINDH",
    contact: "0333-2612781",
  },
  {
    name: "Star Battery & Solar - Tando Mohammad Khan",
    address: "Badin Road, Tando Mohammad Khan",
    city: "Tando Mohammad Khan",
    province: "SINDH",
    contact: "0300-3071343",
  },
  {
    name: "Universal Battery Center - Hyderabad",
    address: "Shop # 3, Haji Sultan Market, Hala Naka, Hyderabad",
    city: "Hyderabad",
    province: "SINDH",
    contact: "0333-2615577",
  },
  {
    name: "Waseem Battery Service - Hyderabad",
    address: "Shop # 13,14 Haji Sultan Market, Hala Naka, Hyderabad",
    city: "Hyderabad",
    province: "SINDH",
    contact: "0300-3012971",
  },
  {
    name: "Zeeshan Battery Service - Hala",
    address: "Main National Highway, Hala",
    city: "Hala",
    province: "SINDH",
    contact: "0300-3023243",
  },
  {
    name: "Abdullah Battery - Islamabad",
    address: "Shop # 14, Akbar Market, G-10 Markaz, Islamabad",
    city: "Islamabad",
    province: "ISLAMABAD",
    contact: "0333-5155630",
  },
  {
    name: "Abid Battery Center - Rawalpindi",
    address: "Shop # 5, City Terminal, Pirwadhai, Rawalpindi",
    city: "Rawalpindi",
    province: "PUNJAB",
    contact: "0333-5120170",
  },
  {
    name: "Al-Hamd Battery Center - Rawalpindi",
    address: "Shop # 12, City Terminal, Pirwadhai, Rawalpindi",
    city: "Rawalpindi",
    province: "PUNJAB",
    contact: "0321-5121334",
  },
  {
    name: "Al-Makkah Battery & Solar - Chakwal",
    address: "Talagang Road, Chakwal",
    city: "Chakwal",
    province: "PUNJAB",
    contact: "0333-5913361",
  },
  {
    name: "Ali Battery Service - Rawalpindi",
    address: "Shop # 6, City Terminal, Pirwadhai, Rawalpindi",
    city: "Rawalpindi",
    province: "PUNJAB",
    contact: "0333-5246237",
  },
  {
    name: "Awan Battery Service - Talagang",
    address: "Chakwal Road, Talagang",
    city: "Talagang",
    province: "PUNJAB",
    contact: "0333-5768560",
  },
  {
    name: "Bismillah Battery & Solar - Attock",
    address: "Kamra Road, Attock",
    city: "Attock",
    province: "PUNJAB",
    contact: "0333-5961445",
  },
  {
    name: "Chaudhry Battery Center - Jhelum",
    address: "G.T Road, Jhelum",
    city: "Jhelum",
    province: "PUNJAB",
    contact: "0300-9512130",
  },
  {
    name: "Faisal Battery Service - Rawalpindi",
    address: "Shop # 10, City Terminal, Pirwadhai, Rawalpindi",
    city: "Rawalpindi",
    province: "PUNJAB",
    contact: "0333-5104430",
  },
  {
    name: "Hafiz Battery Center - Rawalpindi",
    address: "Shop # 2, City Terminal, Pirwadhai, Rawalpindi",
    city: "Rawalpindi",
    province: "PUNJAB",
    contact: "0333-5211510",
  },
  {
    name: "Hamza Battery & Solar - Gujar Khan",
    address: "G.T Road, Gujar Khan",
    city: "Gujar Khan",
    province: "PUNJAB",
    contact: "0300-5226464",
  },
  {
    name: "Irfan Battery Service - Rawalpindi",
    address: "Shop # 7, City Terminal, Pirwadhai, Rawalpindi",
    city: "Rawalpindi",
    province: "PUNJAB",
    contact: "0333-5161472",
  },
  {
    name: "Jan Battery Center - Rawalpindi",
    address: "Shop # 3, City Terminal, Pirwadhai, Rawalpindi",
    city: "Rawalpindi",
    province: "PUNJAB",
    contact: "0321-5000505",
  },
  {
    name: "Kiani Battery Service - Rawalpindi",
    address: "Shop # 8, City Terminal, Pirwadhai, Rawalpindi",
    city: "Rawalpindi",
    province: "PUNJAB",
    contact: "0300-5111456",
  },
  {
    name: "Madina Battery & Solar - Fateh Jang",
    address: "Rawalpindi Road, Fateh Jang",
    city: "Fateh Jang",
    province: "PUNJAB",
    contact: "0333-5463636",
  },
  {
    name: "Malik Battery Center - Islamabad",
    address: "Shop # 15, Akbar Market, G-10 Markaz, Islamabad",
    city: "Islamabad",
    province: "ISLAMABAD",
    contact: "0300-5155630",
  },
  {
    name: "MashaAllah Battery Service - Rawalpindi",
    address: "Shop # 1, City Terminal, Pirwadhai, Rawalpindi",
    city: "Rawalpindi",
    province: "PUNJAB",
    contact: "0333-5121115",
  },
  {
    name: "New Awan Battery Service - Rawalpindi",
    address: "Shop # 14, City Terminal, Pirwadhai, Rawalpindi",
    city: "Rawalpindi",
    province: "PUNJAB",
    contact: "0321-5123456",
  },
  {
    name: "New Kashmir Battery Center - Rawalpindi",
    address: "Shop # 9, City Terminal, Pirwadhai, Rawalpindi",
    city: "Rawalpindi",
    province: "PUNJAB",
    contact: "0300-5121212",
  },
  {
    name: "Pakistan Battery House - Rawalpindi",
    address: "Shop # 4, City Terminal, Pirwadhai, Rawalpindi",
    city: "Rawalpindi",
    province: "PUNJAB",
    contact: "0333-5100100",
  },
  {
    name: "Pothohar Battery & Solar - Rawalpindi",
    address: "Shop # 11, City Terminal, Pirwadhai, Rawalpindi",
    city: "Rawalpindi",
    province: "PUNJAB",
    contact: "0300-5112233",
  },
  {
    name: "Qureshi Battery Service - Rawalpindi",
    address: "Shop # 13, City Terminal, Pirwadhai, Rawalpindi",
    city: "Rawalpindi",
    province: "PUNJAB",
    contact: "0321-5114455",
  },
  {
    name: "Rajput Battery & Solar - Pindigheb",
    address: "Rawalpindi Road, Pindigheb",
    city: "Pindigheb",
    province: "PUNJAB",
    contact: "0333-5858585",
  },
  {
    name: "Rehman Battery Center - Rawalpindi",
    address: "Shop # 15, City Terminal, Pirwadhai, Rawalpindi",
    city: "Rawalpindi",
    province: "PUNJAB",
    contact: "0333-5113344",
  },
  {
    name: "Sachal Battery & Solar - Rawalpindi",
    address: "Shop # 16, City Terminal, Pirwadhai, Rawalpindi",
    city: "Rawalpindi",
    province: "PUNJAB",
    contact: "0300-5115566",
  },
  {
    name: "Star Battery & Solar - Rawalpindi",
    address: "Shop # 17, City Terminal, Pirwadhai, Rawalpindi",
    city: "Rawalpindi",
    province: "PUNJAB",
    contact: "0333-5117788",
  },
  {
    name: "Universal Battery Center - Rawalpindi",
    address: "Shop # 18, City Terminal, Pirwadhai, Rawalpindi",
    city: "Rawalpindi",
    province: "PUNJAB",
    contact: "0321-5119900",
  },
  {
    name: "Zain Battery & Solar - Rawalpindi",
    address: "Shop # 19, City Terminal, Pirwadhai, Rawalpindi",
    city: "Rawalpindi",
    province: "PUNJAB",
    contact: "0300-5110011",
  },
  {
    name: "A.H TRADERS",
    address: "FAISAL GARDEN NEAR JALAL PUR JATTAN ROAD GUJRAT",
    city: "GUJRAT",
    province: "PUNJAB",
    contact: "0300-6214163",
  },
  {
    name: "A.R TRADERS",
    address: "SARAFA BAZAR ALIPUR CHATHA",
    city: "ALIPUR CHATHA",
    province: "PUNJAB",
    contact: "0300-7440401",
  },
  {
    name: "A.S BATTERY CENTRE",
    address: "NEAR JAZZ FRANCHISE ALLAH HO CHOWK JALAL PUR JATTAN",
    city: "JALAL PUR JATTAN",
    province: "PUNJAB",
    contact: "0334-4340533",
  },
  {
    name: "ABBAS BATTERY CENTER",
    address: "NEAR GENERAL BUS STAND G.T ROAD GUJRAT",
    city: "GUJRAT",
    province: "PUNJAB",
    contact: "0345-6852277",
  },
  {
    name: "ABDULLAH BATTERY & SOLAR SYSTEM",
    address: "NEAR DERA KARAM SHAH DHOK GHAZIAN G.T ROAD GUJRAT",
    city: "GUJRAT",
    province: "PUNJAB",
    contact: "0311-1718000",
  },
  {
    name: "ABID BATTERY SERVICE",
    address: "OLD G.T ROAD NEAR FRUIT MANDI GUJRANWALA",
    city: "GUJRANWALA",
    province: "PUNJAB",
    contact: "0321-6450684",
  },
  {
    name: "ABID BATTERY SERVICE - HAFIZABAD",
    address: "VANAIKE ROAD HAFIZABAD",
    city: "HAFIZABAD",
    province: "PUNJAB",
    contact: "0341-4712435",
  },
  {
    name: "AL FAROOQ BATTERY CENTRE",
    address: "NEAR CIVIL HOSPITAL WAZIRABAD",
    city: "WAZIRABAD",
    province: "PUNJAB",
    contact: "0301-6404780",
  },
  {
    name: "AL GHAFFAR BATTERY SERVICE",
    address: "KHIALI BYPASS GUJRANWALA",
    city: "GUJRANWALA",
    province: "PUNJAB",
    contact: "0321-6411516",
  },
  {
    name: "AL HAMD BATTERY CENTER",
    address: "SHOP NO.60 AUTO MARKET GUJRANWALA",
    city: "GUJRANWALA",
    province: "PUNJAB",
    contact: "0321-6421833",
  },
  {
    name: "AL MAKKAH BATTERY CENTRE",
    address: "CIRCULAR ROAD NEAR PASSPORT OFFICE GUJRANWALA",
    city: "GUJRANWALA",
    province: "PUNJAB",
    contact: "0300-9642578",
  },
  {
    name: "AL REHMAN BATTERY CENTRE",
    address: "DINA NAGAR ROAD GUJRANWALA",
    city: "GUJRANWALA",
    province: "PUNJAB",
    contact: "0300-6447547",
  },
  {
    name: "AL SADIQ BATTERY CENTRE",
    address: "GONDLANWALA ROAD GUJRANWALA",
    city: "GUJRANWALA",
    province: "PUNJAB",
    contact: "0300-9644023",
  },
  {
    name: "ALI BATTERY CENTRE - GUJRAT",
    address: "G.T ROAD NEAR FAWRA CHOWK GUJRAT",
    city: "GUJRAT",
    province: "PUNJAB",
    contact: "0300-6228784",
  },
  {
    name: "ALI BATTERY CENTRE - SAMBRIAL",
    address: "WAZIRABAD ROAD SAMBRIAL",
    city: "SAMBRIAL",
    province: "PUNJAB",
    contact: "0300-7117173",
  },
  {
    name: "ALI BATTERY CENTRE - SIALKOT",
    address: "HAJIPURA ROAD SIALKOT",
    city: "SIALKOT",
    province: "PUNJAB",
    contact: "0300-6101915",
  },
  {
    name: "AMANAT BATTERY SERVICE",
    address: "G.T ROAD GHAKHAR MANDI",
    city: "GHAKHAR MANDI",
    province: "PUNJAB",
    contact: "0300-6430349",
  },
  {
    name: "ARSHAD BATTERY CENTRE",
    address: "RAILWAY ROAD PASRUR",
    city: "PASRUR",
    province: "PUNJAB",
    contact: "0300-6126650",
  },
  {
    name: "ASAD BATTERY CENTRE",
    address: "DASKA ROAD NEAR LARI ADDA SIALKOT",
    city: "SIALKOT",
    province: "PUNJAB",
    contact: "0322-7901804",
  },
  {
    name: "ASHRAF BATTERY SERVICE",
    address: "G.T ROAD NEAR GENERAL BUS STAND GUJRANWALA",
    city: "GUJRANWALA",
    province: "PUNJAB",
    contact: "0321-6458550",
  },
  {
    name: "ASKARI BATTERY CENTRE",
    address: "G.T ROAD NEAR CHENAB BRIDGE WAZIRABAD",
    city: "WAZIRABAD",
    province: "PUNJAB",
    contact: "0301-6415758",
  },
  {
    name: "ASLAM BATTERY CENTRE",
    address: "SIALKOT ROAD NEAR GONDLANWALA CHOWK GUJRANWALA",
    city: "GUJRANWALA",
    province: "PUNJAB",
    contact: "0321-6421422",
  },
  {
    name: "AWAN BATTERY SERVICE - GUJRANWALA",
    address: "G.T ROAD NEAR GENERAL BUS STAND GUJRANWALA",
    city: "GUJRANWALA",
    province: "PUNJAB",
    contact: "0321-6450015",
  },
  {
    name: "AZAM BATTERY CENTRE",
    address: "G.T ROAD NEAR FAWRA CHOWK GUJRAT",
    city: "GUJRAT",
    province: "PUNJAB",
    contact: "0300-6213451",
  },
  {
    name: "B.A TRADERS",
    address: "G.T ROAD NEAR GENERAL BUS STAND GUJRANWALA",
    city: "GUJRANWALA",
    province: "PUNJAB",
    contact: "0321-7440401",
  },
  {
    name: "BASHIR BATTERY SERVICE",
    address: "G.T ROAD LALAMUSA",
    city: "LALAMUSA",
    province: "PUNJAB",
    contact: "0345-6805556",
  },
  {
    name: "Nihal Battery House - Jehangira",
    address: "Near UBL Bank, G.T Road Jehangira, District Nowshera",
    city: "Jehangira",
    province: "KPK",
    contact: "0312-5986486",
  },
  {
    name: "Peshawar Battery Center - Mardan",
    address: "Near Railway Phatak Charsadda Chowk, Mardan",
    city: "Mardan",
    province: "KPK",
    contact: "0307-5758003",
  },
  {
    name: "Peshawar Battery Center - Nowshera",
    address: "Shop#21, Farooq Stadium Plaza, G.T Road, Nowshera Cantt",
    city: "Nowshera",
    province: "KPK",
    contact: "0301-8845317/0315-9231509",
  },
  {
    name: "Rahim Traders Energy Solution - Peshawar",
    address: "Ring Road Near Dewan Hayat Gathering Hall, Peshawar",
    city: "Peshawar",
    province: "KPK",
    contact: "0334-9154639",
  },
  {
    name: "Raza Tyre And Battery Center - Swabi",
    address: "Mardan Road, Swabi",
    city: "Swabi",
    province: "KPK",
    contact: "0345-8005010/0333-9432892",
  },
  {
    name: "Sajid Battery Centre - Toppi",
    address: "Swabi Road, Khan Zaman Market, Near Meezan Bank, Topi",
    city: "Toppi",
    province: "KPK",
    contact: "0315-4871718",
  },
  {
    name: "Saleem Electronic Battery & Solar Centre - Totalai",
    address: "Saleem Market, Near Khyber Bank, Totalai, Buner",
    city: "Totalai",
    province: "KPK",
    contact: "0342-9748127/0316-0935954",
  },
  {
    name: "Sartaj Autos Electric Parts Center - Timergara",
    address: "Shoba Market, Timergara",
    city: "Timergara",
    province: "KPK",
    contact: "0301-8889501/301-8016902",
  },
  {
    name: "Sawab Gul Battery & Solar House - Sadda",
    address: "Shaheen Market, Sadda",
    city: "Sadda",
    province: "KPK",
    contact: "0303-9012190/0302-5654286",
  },
  {
    name: "Seven Star Electronics & Battery Commission Agent - Bajroh",
    address: "Main Bazar Anayat Killi, District, Bajorh",
    city: "Bajaur",
    province: "KPK",
    contact: "0300-4486839",
  },
  {
    name: "Shakir Enterprises - Peshawar",
    address: "Jamil Chowk, Ring Road, Peshawar",
    city: "Peshawar",
    province: "KPK",
    contact: "0316-9025099",
  },
  {
    name: "Shehzad Battery Centre - D.I.Khan",
    address: "",
    city: "Dera Ismail Khan",
    province: "KPK",
    contact: "",
  },
  {
    name: "United Auto & Battery House - Batkhela",
    address: "Near Old Dir Adda, Main Bazar, Batkhela, District Malakand",
    city: "Batkhela",
    province: "KPK",
    contact: "0348-9111366",
  },
  {
    name: "Ahmad Battery & UPS Sale & Service - Lahore",
    address: "Fazal Market Cannal Bank Road, Thokar Niaz Baig, Lahore",
    city: "Lahore",
    province: "PUNJAB",
    contact: "0300-8029125",
  },
  {
    name: "Al Ameer Traders - Ellahabad",
    address: "Allahabad Chunian Road",
    city: "Ellahabad",
    province: "PUNJAB",
    contact: "0309-2614302",
  },
  {
    name: "Ali & Company - Lahore",
    address: "391, Block D3, Main WAPDA Avenue, WAPDA Town, Lahore",
    city: "Lahore",
    province: "PUNJAB",
    contact: "0321-8262505",
  },
  {
    name: "Ali Battery Service - Lahore",
    address: "Opposite Kamahan Meto Station, 17-K.M. Ferozpur Road, Lahore",
    city: "Lahore",
    province: "PUNJAB",
    contact: "0300-8801701",
  },
  {
    name: "Ameen Traders - Lahore",
    address: "Chowk Misry Shah, Near Safed Masjid, Lahore",
    city: "Lahore",
    province: "PUNJAB",
    contact: "0326-1422809",
  },
  {
    name: "Amin Battery Service - Sheikhupura",
    address: "Faisalabad Road, Sheikhupura",
    city: "Sheikhupura",
    province: "PUNJAB",
    contact: "0333-4009247",
  },
  {
    name: "AR Battery - Lahore",
    address: "16 KM, Ferozpur Road, Kamahan Meto Stop, Bank Stop, Iqbal Town, Lahore",
    city: "Lahore",
    province: "PUNJAB",
    contact: "0307-6847310/0308-4917593",
  },
  {
    name: "Arain Traders - Ellahabad",
    address: "Chunian Road, Near Lahori Marriage Hall, Ellahabad, Tehsil Chunian, District Kasur",
    city: "Ellahabad",
    province: "PUNJAB",
    contact: "0307-4003580",
  },
  {
    name: "Asad Trading Company - Lahore",
    address: "Shop#6, New LMC Market Bdami Bagh, Lahore",
    city: "Lahore",
    province: "PUNJAB",
    contact: "0300-4238439",
  },
  {
    name: "Bismillah Battery Service - Wazirabad",
    address: "Masjid Musafiran, Near Sapal Market, G.T. Road Wazirabad",
    city: "Wazir Abad",
    province: "PUNJAB",
    contact: "0300-4263721",
  },
  {
    name: "Bismillah Battery Specialist - Kasur",
    address: "Pull Qatal Garhi, Katchery Road, Near Mukarma Bank, Kasur",
    city: "Kasur",
    province: "PUNJAB",
    contact: "0321-3220291",
  },
  {
    name: "Bismillah Battery Store - Lahore",
    address: "Ghulam Muhammad Building, Sheikhupura Road, Jiya Mosa, Shahdara, Lahore",
    city: "Lahore",
    province: "PUNJAB",
    contact: "0321-4491782/0332-4701754",
  },
  {
    name: "Butt Electrician - Manga Mandi",
    address: "Multan Road, Rajpoot Nagar Manga Mandi, Lahore",
    city: "Manga Mandi",
    province: "PUNJAB",
    contact: "0304-4888817/0345-4701318",
  },
  {
    name: "Energy Zone - Gujrat",
    address: "",
    city: "Gujrat",
    province: "PUNJAB",
    contact: "",
  },
  {
    name: "Exide Sale And Service Centre - Okara",
    address: "G.T Road, Okara",
    city: "Okara",
    province: "PUNJAB",
    contact: "0300-8751407",
  },
  {
    name: "Golden Traders - Pattoki",
    address: "Multan Road, Pattoki",
    city: "Pattoki",
    province: "PUNJAB",
    contact: "0300-9437894",
  },
  {
    name: "Hassan Traders - Sialkot",
    address: "Ghalib Road, Puli Kammanwali, Sialkot",
    city: "Sialkot",
    province: "PUNJAB",
    contact: "0300-1611829",
  },
  {
    name: "Ittefaq Battery House - Nankana Sahib",
    address: "Shop# 1979, Near Admore Pump, Lorry Adda Mangtanwala Road, Nankana Sahib",
    city: "Nankana Sahib",
    province: "PUNJAB",
    contact: "0300-8035716",
  },
  {
    name: "Japan Batteries - Narowal",
    address: "Zaffarwal Chowk, Circular Road, Narowal",
    city: "Narowal",
    province: "PUNJAB",
    contact: "0300-5016501",
  },
  {
    name: "Kohat Traders - Lahore",
    address: "Outside Masti Gate, Circular Road, Badami Bagh, Lahore",
    city: "Lahore",
    province: "PUNJAB",
    contact: "0322-4395535",
  },
  {
    name: "M/S Al Mecca Enterprises - Gujranwala",
    address: "Opp. Iqbal High School, Near Totall Petrol Pump, G.T Road , Gujranwala",
    city: "Gujranwala",
    province: "PUNJAB",
    contact: "",
  },
  {
    name: "M/S Citi Traders - Lahore",
    address: "Samsani Road near Pizza Hut Johar Town, Lahore",
    city: "Lahore",
    province: "PUNJAB",
    contact: "0305-3012815",
  },
  {
    name: "M/S Ismail Traders - Ferozwala",
    address: "Adil Battery Service, G.T Road, Muridke",
    city: "Ferozwala",
    province: "PUNJAB",
    contact: "0304-4403501/0333-4511682",
  },
  {
    name: "Madina Battery Service - Lalamusa",
    address: "Oppsite side, Sabzi Mandi , GT Road Lalamusa",
    city: "Lalamusa",
    province: "PUNJAB",
    contact: "0317-7346946",
  },
  {
    name: "Makkah Battery Center - Lahore",
    address: "Samsani Road, Near Shadewal Chowk, Johar Town, Lahore",
    city: "Lahore",
    province: "PUNJAB",
    contact: "0321-6509001",
  },
  {
    name: "Mansha Battery Service - Sheikhupura",
    address: "Faisalabad Road, Sheikhupura",
    city: "Sheikhupura",
    province: "PUNJAB",
    contact: "0321-4865611",
  },
  {
    name: "Masha Allah Battery Service - Khudian Khas",
    address: "New Lari Adda, Depalpur Road, Near NADRA Office, Khudian Khas",
    city: "Khudian Khas",
    province: "PUNJAB",
    contact: "0300-8586779",
  },
  {
    name: "Master Battery Traders - Lahore",
    address: "Multan Road, Opposite Mansoora, Multan Chungi, Lahore",
    city: "Lahore",
    province: "PUNJAB",
    contact: "0300-4930949",
  },
  {
    name: "Muhammad Ali Battery Service - Kasur",
    address: "Near Chowk Qadir Abad Road, Kasur",
    city: "Kasur",
    province: "PUNJAB",
    contact: "0321-6571662",
  },
  {
    name: "Muhammadi Battery & Oil Traders - Lahore",
    address: "P-334 Block-6 B-01, Town Ship Lahore",
    city: "Lahore",
    province: "PUNJAB",
    contact: "0323-1234562",
  },
  {
    name: "Nadeem Traders - Raiwind",
    address: "Opposite Gourmet Bakery, Lahore Road, Raiwind, Lahore",
    city: "Lahore",
    province: "PUNJAB",
    contact: "0302-4561045",
  },
  {
    name: "Naeem Traders - Lahore",
    address: "325 G.T.Road, Daroghawala, Lahore",
    city: "Lahore",
    province: "PUNJAB",
    contact: "0308-4444357",
  },
  {
    name: "New Rajput Battery - Lahore",
    address: "Shop#23, Montgomary Road, Lahore",
    city: "Lahore",
    province: "PUNJAB",
    contact: "0321-0521000/0323-7104079",
  },
  {
    name: "Nobel Traders - Lahore",
    address: "Noshahi Battery Akbar Chowk Town Ship, Lahore",
    city: "Lahore",
    province: "PUNJAB",
    contact: "0306-4068927",
  },
  {
    name: "Pakistan Battery - Lahore",
    address: "Ghulam Muhammad Building Sheikhupura Road, Shadara, Lahore",
    city: "Lahore",
    province: "PUNJAB",
    contact: "0300-0388354",
  },
  {
    name: "Pakistan Battery Traders - Gujranwala",
    address: "Opposite Iqbal High School, G.T Road, Gujranwala",
    city: "Gujranwala",
    province: "PUNJAB",
    contact: "0300-0471441",
  },
  {
    name: "Punjab Traders - Daska",
    address: "Near Shell Petrol Pump, Circular Road, Daska",
    city: "Daska",
    province: "PUNJAB",
    contact: "0305-8712244",
  },
  {
    name: "Sadiq Battery Agency - Lahore",
    address: "Dyal Singh Mansion, Shahrah-e-Quaid-e-Azam, Lahore",
    city: "Lahore",
    province: "PUNJAB",
    contact: "0332-8488916",
  },
  {
    name: "Sajjad Battery House - Lahore",
    address: "Shop# E/193/2, Bank Stop Main Walton Road, Lahore",
    city: "Lahore",
    province: "PUNJAB",
    contact: "0321-4367254",
  },
  {
    name: "Shahbaz Battery Service - Farooq Abad",
    address: "Lahore Sargodha Road, Near Larri Adda Farooq Abad, Sheikhpura",
    city: "Farooq Abad",
    province: "PUNJAB",
    contact: "0322-7273824",
  },
  {
    name: "Shahzad Traders - Gujrat",
    address: "",
    city: "Gujrat",
    province: "PUNJAB",
    contact: "0300-6285637/0331-6285637",
  },
  {
    name: "Solergy Zone (Private) Limited - Lahore",
    address: "Office # 708, Al - Hafeez Shopping Mall, Main Boulevard, Gulberg-III, Lahore",
    city: "Lahore",
    province: "PUNJAB",
    contact: "0322-4292415",
  },
  {
    name: "Star Enterprises - Lahore",
    address: "Near Niazi Stand, Bund Road, Lahore",
    city: "Lahore",
    province: "PUNJAB",
    contact: "0300-6986600",
  },
  {
    name: "Tanveer Battery Center - Kamokee",
    address: "Shop#1, Near Bank of Punjab, G.T Road Kamokee, Gujranwala",
    city: "Kamoki",
    province: "PUNJAB",
    contact: "0300-6474574",
  },
  {
    name: "Umer Battery Service - Lahore",
    address: "Shop#35, Street#9, New Iqbal Park, Opposite Adil Hospital, DHA, Lahore",
    city: "Lahore",
    province: "PUNJAB",
    contact: "0300-9415522",
  },
  {
    name: "Waqas Battery Service - Ali Pur Chattha",
    address: "Near Tayyab Motor Showroom, Qadir Abad Road, Ali Pur Chattha",
    city: "Ali Pur Chattha",
    province: "PUNJAB",
    contact: "0300-8290574",
  },
  {
    name: "Zayan Distributer - Lahore",
    address: "V.142, KB Colony, Air Port Road, Lahore",
    city: "Lahore",
    province: "PUNJAB",
    contact: "",
  },
  {
    name: "Zeb Battery Center - Lahore",
    address: "42 Aziz Road, Misri Shah Opposite WASA office, Chowk Nakhuds, Lahore",
    city: "Lahore",
    province: "PUNJAB",
    contact: "0300-9045551",
  },
  {
    name: "M/S Battery Dealer - Lahore",
    address: "Building 17A, Block H1, Sabzazar, Lahore",
    city: "Lahore",
    province: "PUNJAB",
    contact: "",
  },
  {
    name: "Adnan Bhutta Battery Center - Multan",
    address: "Al Tamash Road Gujjar Khadda, Near Gull Khan Kabaria, Multan",
    city: "Multan",
    province: "PUNJAB",
    contact: "0300-8542990",
  },
  {
    name: "Ahmad Battery and Solar System - Mailsi",
    address: "Multan Road, Mailsi",
    city: "Mailsi",
    province: "PUNJAB",
    contact: "0300-7727408",
  },
  {
    name: "Ahmad Traders - Multan",
    address: "Near Ideal Mall, Chungi#6, Bosan Road, Multan",
    city: "Multan",
    province: "PUNJAB",
    contact: "0302-3521432/0312-0111432",
  },
  {
    name: "Ajmal Traders - Khan Pur",
    address: "Chowk Deen Pur, Air Port Road, Khan Pur District, Rahim Yar Khan",
    city: "Khan Pur",
    province: "PUNJAB",
    contact: "0300-4653572",
  },
  {
    name: "Al Makka Battery & Solar System - Muhammad Pur Dewan",
    address: "Dera Road, Muhammad Pur Dewan, Tehsil Jampur, District Rajanpur",
    city: "Muhammad Pur Dewan",
    province: "PUNJAB",
    contact: "0333-6459345",
  },
  {
    name: "Al-Basit Traders - Rahim Yar Khan",
    address: "Khanpur Road, Near Punjab College, Rahim Yar Khan",
    city: "Rahim Yar Khan",
    province: "PUNJAB",
    contact: "0300-8679922",
  },
  {
    name: "Al-Nawaz Traders - Multan",
    address: "Shop#1,Volta Market, Vehari Chowk, Multan",
    city: "Multan",
    province: "PUNJAB",
    contact: "0333-6105632",
  },
  {
    name: "Awais Battery Center - Jampur",
    address: "Near Traffic Chowk, Dera Road, Jampur",
    city: "Jampur",
    province: "PUNJAB",
    contact: "0336-6444889",
  },
  {
    name: "Awami Corporation - Arif Wala",
    address: "Near General Bus Stand Pakpattan Road, Arif Wala",
    city: "Arif Wala",
    province: "PUNJAB",
    contact: "0345-6949930",
  },
  {
    name: "Bhayya Gee Battery Centre - Ahmedpur East",
    address: "Chowk Chacha Bsti, General Bus Stand, Ahmedpur East.",
    city: "Ahmedpur East",
    province: "PUNJAB",
    contact: "0300-6859699",
  },
  {
    name: "Cheema Autos & Battery Center - Liaquat Pur",
    address: "Khanpur Road, Liaquat Pur",
    city: "Liaquat Pur",
    province: "PUNJAB",
    contact: "0300-8020152",
  },
  {
    name: "Ehsan Tyre & Battery Centre - Multan",
    address: "Masoom Shah Road, Opposite Alfalah Bank, Qazafi Chowk, Multan",
    city: "Multan",
    province: "PUNJAB",
    contact: "0300-7184007",
  },
  {
    name: "Energy Source - Bahawalpur",
    address: "Shop no.13 Multan road near Sirani Masjid Bahawalpur",
    city: "Bahawalpur",
    province: "PUNJAB",
    contact: "0300-9681555",
  },
  {
    name: "Fugi Battery Service - Chishtian",
    address: "Cenima Road, Near Nazi Adda, Chishtian",
    city: "Chishtian",
    province: "PUNJAB",
    contact: "0300-6986809/0300-7544686",
  },
  {
    name: "Hafeez Muslim Battery Centre - Sadiqabad",
    address: "K.L.P Road, Near, Ghosia Chowk Sadiq Abad, Rahim Yar Khan Sadiqabad",
    city: "Sadiqabad",
    province: "PUNJAB",
    contact: "0306-5630091",
  },
  {
    name: "Hamza Battery Traders - Multan",
    address: "",
    city: "Multan",
    province: "PUNJAB",
    contact: "",
  },
  {
    name: "Haq Bahoo Battery & Solar UPS Centre - Sadiq Abad",
    address: "Ghousia Chowk, K.L.P Road, Sadiqabad",
    city: "Sadiqabad",
    province: "PUNJAB",
    contact: "0300-1774770/0310-8760000",
  },
  {
    name: "Hassan Battery Services - Layyah",
    address: "Katchery Road, General Bus Stand , Layyah",
    city: "Layyah",
    province: "PUNJAB",
    contact: "0303-6462441",
  },
  {
    name: "Hassan Battery Services - Multan",
    address: "30-K, General Bus Stand, Vehari Chowk, Multan",
    city: "Multan",
    province: "PUNJAB",
    contact: "0303-7206373",
  },
  {
    name: "Hussnain Battery Service - Faqir Wali",
    address: "Near Pathan Masjid, Highway Road, Faqirwali",
    city: "Faqeer Wali",
    province: "PUNJAB",
    contact: "0306-7577590/0346-8827473",
  },
  {
    name: "Imran Battery Center & Solar System - Rajan Pur",
    address: "Dera Ghazi Khan Road, Rajan Pur",
    city: "Rajan Pur",
    province: "PUNJAB",
    contact: "0334-2984631",
  },
  {
    name: "Imran Gulzar Battery Service - Chowk Azam",
    address: "Multan Road, Chowk Azam",
    city: "Chowk Azam",
    province: "PUNJAB",
    contact: "0301-7849354",
  },
  {
    name: "Iqbal Battery Service - Layyah",
    address: "General Bus Stand, Layyah",
    city: "Layyah",
    province: "PUNJAB",
    contact: "0302-8762121",
  },
  {
    name: "Kamran Battery Center - Layyah",
    address: "Katchery Road, Near General Bus Stand, Layyah",
    city: "Layyah",
    province: "PUNJAB",
    contact: "0300-8762121",
  },
  {
    name: "Khan Battery & UPS Center - Muzaffar Garh",
    address: "Jhang More, Opposite Shell Pump, Muzaffar Garh",
    city: "Muzafargarh",
    province: "PUNJAB",
    contact: "0300-6868708",
  },
  {
    name: "Khan Battery Center - Multan",
    address: "Azmat Wasti Road, Dera Adda, Multan",
    city: "Multan",
    province: "PUNJAB",
    contact: "",
  },
  {
    name: "Khanewal Traders - Kabirwala",
    address: "General Bus Stand, Kabirwala",
    city: "Kabir Wala",
    province: "PUNJAB",
    contact: "0300-0799867/0333-1022340",
  },
  {
    name: "Khawaja Imran Haider Autos - Uch Sharif",
    address: "Kutaney Wali Pull, Ali Pur Road, Uch Sharif",
    city: "Uch Sharif",
    province: "PUNJAB",
    contact: "0306-4731549",
  },
  {
    name: "M S Traders - Khanewal",
    address: "Punjab Small Industrial Estate Jahanian Road, Khanewal",
    city: "Khanewal",
    province: "PUNJAB",
    contact: "0300-6885596/0312-7606447",
  },
  {
    name: "M/s Chaudhary Battery Traders - Jahanian",
    address: "Khanewal Road, Bypass Chowk, Jahanian",
    city: "Jahanian",
    province: "PUNJAB",
    contact: "0300-7596632",
  },
  {
    name: "Madina Battery Service - Kamlia",
    address: "Iqbal Town. Faisalabad Road, Kamlia",
    city: "Kamlia",
    province: "PUNJAB",
    contact: "0317-1690620",
  },
  {
    name: "Majeed Battery Center - Alipur",
    address: "Ghani Ghoth Road, Tehsil Alipur, District Muzaffar Garh",
    city: "Alipur",
    province: "PUNJAB",
    contact: "0315-7679295",
  },
  {
    name: "Makka Battery Service - Multan",
    address: "Chungi#06, Bosan Road, Multan",
    city: "Multan",
    province: "PUNJAB",
    contact: "0300-6349662",
  },
  {
    name: "Muzamil Traders - D.G Khan",
    address: "General Bus Stand, D.G.Khan",
    city: "Dera Ghazi Khan",
    province: "PUNJAB",
    contact: "0347-4887440",
  },
  {
    name: "Nagri Peer Pathan Battery Store - Tonsa Sharif",
    address: "Hashmi Chowk, Tonsa Sharif",
    city: "Tonsa Sharif",
    province: "PUNJAB",
    contact: "0333-5894684",
  },
  {
    name: "New Pakistan Battery Centre - Burewala",
    address: "Lahore, Road, Burewala, Vehari Burewala",
    city: "Burewala",
    province: "PUNJAB",
    contact: "0308-8076432",
  },
  {
    name: "New Rasheed Battery Service - Multan",
    address: "128 B, Vehari Chowk, General Bus Stand, Multan",
    city: "Multan",
    province: "PUNJAB",
    contact: "0300-8421599/0303-3631910",
  },
  {
    name: "Noor Ulain Traders - Khanewal",
    address: "Fazal Park Road, Khanewal",
    city: "Khanewal",
    province: "PUNJAB",
    contact: "0334-6812030",
  },
  {
    name: "Pakistan Battery Center - Chishtian",
    address: "",
    city: "Chishtian",
    province: "PUNJAB",
    contact: "",
  },
  {
    name: "Pakistan Battery Traders - Mian Channu",
    address: "Amin Trade Centre Near MCB Bank Larri Adda G.T Road, Mian Channu",
    city: "Mian Channu",
    province: "PUNJAB",
    contact: "0323-7590342",
  },
  {
    name: "Punjab Battery And Solar System - Lodhran",
    address: "Adda, Permit, Near PSO Pump, Lodhran",
    city: "Lodhran",
    province: "PUNJAB",
    contact: "0303-6750590/0333-6806060",
  },
  {
    name: "Rafiq Battery Service - Multan",
    address: "Dera Adda Chowk, Multan",
    city: "Multan",
    province: "PUNJAB",
    contact: "0302-7308705/0302-7434004",
  },
  {
    name: "Saim Traders - Rahim Yar Khan",
    address: "Belgium Chowk, Shahi Road, Rahim Yar Khan",
    city: "Rahim Yar Khan",
    province: "PUNJAB",
    contact: "0300-6713929",
  },
  {
    name: "Sami Battery Service - Fatehpur",
    address: "M M Road, Fateh Pur",
    city: "Fateh Pur",
    province: "PUNJAB",
    contact: "0300-2850175",
  },
  {
    name: "Shaban Electronics - Alipur",
    address: "",
    city: "Alipur",
    province: "PUNJAB",
    contact: "",
  },
  {
    name: "Shahid Niaz Battery Centre - Muzaffar Garh",
    address: "Ali Pur Road, Muzaffar Garh",
    city: "Muzafargarh",
    province: "PUNJAB",
    contact: "0300-6862456",
  },
  {
    name: "Shoaib Traders - D.G Khan",
    address: "Schani Colony, Near Pull Piyary Wali, D.G Khan",
    city: "Dera Ghazi Khan",
    province: "PUNJAB",
    contact: "0300-5420000",
  },
  {
    name: "Sohail Anwar & Co - Sahiwal",
    address: "Railway Road, Sahiwal",
    city: "Sahiwal",
    province: "PUNJAB",
    contact: "0300-6907423",
  },
  {
    name: "Talha Traders - Multan",
    address: "26-K, General Bus Stand, Vehari Chowk, Multan",
    city: "Multan",
    province: "PUNJAB",
    contact: "0316-8583974",
  },
  {
    name: "Yousaf  Battery And Repairing Center - Kot Samaba",
    address: "",
    city: "Kot Samaba",
    province: "PUNJAB",
    contact: "",
  },
  {
    name: "Zayan Bajwa Battery Center - Rajan Pur",
    address: "Dera, road Rajanpur",
    city: "Rajan Pur",
    province: "PUNJAB",
    contact: "0331-6002304",
  },
  {
    name: "Abdul Samad Battery - Quetta",
    address: "",
    city: "Quetta",
    province: "BALOCHISTAN",
    contact: "",
  },
  {
    name: "Akram Oil Traders - Chaman",
    address: "Shop No.2, Qandhari, Bazar, Killa Abdullah, Chaman",
    city: "Chammon",
    province: "BALOCHISTAN",
    contact: "0345-8871701",
  },
  {
    name: "Al Madni Traders - Panjgur",
    address: "Bismillah Chowk, Near HBL, Chitkhan Bazar. Panjgur",
    city: "Panjgur",
    province: "BALOCHISTAN",
    contact: "0334-0200780",
  },
  {
    name: "Balochistan Battery Zone And General Order Supplier - Quetta",
    address: "",
    city: "Quetta",
    province: "BALOCHISTAN",
    contact: "",
  },
  {
    name: "Jeelani Agha Autos Battery Zone - Quetta",
    address: "Old Truck Stand, Street#1, Shop#81 Quetta",
    city: "Quetta",
    province: "BALOCHISTAN",
    contact: "0311-8459834",
  },
  {
    name: "Khalid Battery Zone - Quetta",
    address: "Shop#1, Raisani Center Double Road, Quetta",
    city: "Quetta",
    province: "BALOCHISTAN",
    contact: "0332-7824030",
  },
  {
    name: "M/S E-Cool Center - Quetta",
    address: "Shop#1, Double Road, Zarghoon Town, Quetta",
    city: "Quetta",
    province: "BALOCHISTAN",
    contact: "0336-2219326",
  },
  {
    name: "New Muhammadi Battery Zone - Quetta",
    address: "Mir Ghai Khan Chowk Quetta",
    city: "Quetta",
    province: "BALOCHISTAN",
    contact: "",
  },
  {
    name: "Shalimar Battery Agency - Loralai",
    address: "New Adda, Zhob Road, Loralai",
    city: "Loralai",
    province: "BALOCHISTAN",
    contact: "0301-3793300",
  },
  {
    name: "Wali Tractors And Battery Zone - Quetta",
    address: "Circular Road, Quetta",
    city: "Quetta",
    province: "BALOCHISTAN",
    contact: "0306-3831331",
  },
  {
    name: "Yaseen Battery Zone - Quetta",
    address: "Circular Road, Quetta",
    city: "Quetta",
    province: "BALOCHISTAN",
    contact: "0300-9387788",
  },
  {
    name: "Yasin Zai Enterprises - Quetta",
    address: "Mehmood Hotel, Near Circular Road Corner Ali Bhai Road, Quetta",
    city: "Quetta",
    province: "BALOCHISTAN",
    contact: "0336-8168122",
  },
  {
    name: "A 2 Z Solar System - Rawalpindi",
    address: "Shop No. 1/2, Street#3, Misrial Road, Dhoke Syedan Chowk, Rawalpindi.",
    city: "Rawalpindi",
    province: "PUNJAB",
    contact: "0310-6660333",
  },
  {
    name: "Abbottabad Battery Centre - Abbottabad",
    address: "Opposite Sui Gas Office, Jab Pull, Manshera Road, Abbottobad",
    city: "Abbotabad",
    province: "KPK",
    contact: "0316-7041982",
  },
  {
    name: "Ali Traders - Rawalpindi",
    address: "Dheri Hasan Abad, Near Masjid Sheikhan, COD Road, Rawalpindi",
    city: "Rawalpindi",
    province: "PUNJAB",
    contact: "0333-5395652",
  },
  {
    name: "Altaf Battery Traders - Batagram",
    address: "Near PSO Pump, Sarhad Market, Batagram",
    city: "Batagram",
    province: "KPK",
    contact: "0322-9555155",
  },
  {
    name: "Anoosh And Shafel Traders - Rawalpindi",
    address: "Shop#4 Pindi Cricket Stadium Road, Rawalpindi",
    city: "Rawalpindi",
    province: "PUNJAB",
    contact: "0333-5297132",
  },
  {
    name: "Aqib Battery Centre - Islamabad",
    address: "Lehtrar Road Near Rawal Hospital, Khana Dake, Islamabad",
    city: "Islamabad",
    province: "ISLAMABAD",
    contact: "0333-5405238/0301-5631267/",
  },
  {
    name: "Ashfaq Traders  - Dinga",
    address: "Kharain Road, Dinga",
    city: "Kharian",
    province: "PUNJAB",
    contact: "0336-6665465",
  },
  {
    name: "Asia Batteries Services - Tarnol",
    address: "Asia Batteries Services Main G.T Road Near Ameer mouwiya Market Tarnol",
    city: "Islamabad",
    province: "ISLAMABAD",
    contact: "0331-3027333",
  },
  {
    name: "ASR Traders and Builders Private Limited",
    address: "Office#05, Prime Center Farooq Market, G-13/3, Islamabad",
    city: "Islamabad",
    province: "ISLAMABAD",
    contact: "0346-7863132/0335-5226667",
  },
  {
    name: "CH Battery Agency - Rawalpindi",
    address: "Street#135, Tahli Mori, Rawalpindi",
    city: "Rawalpindi",
    province: "PUNJAB",
    contact: "0310-5006197/0319-7839839",
  },
  {
    name: "Chontra Battery Agency and UPS - Rawalpindi",
    address: "Chakri Road, Biscuit Factory Chowk, Rawalpindi",
    city: "Rawalpindi",
    province: "PUNJAB",
    contact: "0334-5055826",
  },
  {
    name: "Gujjar Battery Center - Islamabad",
    address: "Simly Dam Road, Bhara Kahu, Islamabad",
    city: "Islamabad",
    province: "ISLAMABAD",
    contact: "0315-5993726/0346-0511283",
  },
  {
    name: "Gujrat Battery - Rawat",
    address: "Main G.T Road, Rawat, Islamabad",
    city: "Islamabad",
    province: "ISLAMABAD",
    contact: "0300-5334905",
  },
  {
    name: "Hafiz Battery Center - Talagang",
    address: "Shop#3, Sunny Market, Mianwali Road, Near Chowk Siddiqabad, Talagang",
    city: "Talagang",
    province: "PUNJAB",
    contact: "",
  },
  {
    name: "Hafiz Battery Services - Jand",
    address: "Makhad Road, Lari Adda, Jand, Attock",
    city: "Jand",
    province: "PUNJAB",
    contact: "",
  },
  {
    name: "Hamza Traders - Chakwal",
    address: "Main Talagang Road, Chakwal",
    city: "Chakwal",
    province: "PUNJAB",
    contact: "0334-8717312",
  },
  {
    name: "Hanzla Traders - Rawalpindi",
    address: "Opp Shafi Hospital, Dhoke Major, Rawat",
    city: "Rawalpindi",
    province: "PUNJAB",
    contact: "",
  },
  {
    name: "Haroon Traders - Gilgit",
    address: "Liaqat Market, Airport Road,  Gilgit",
    city: "Gilgit",
    province: "Gilgit Baltistan",
    contact: "0300-9778797",
  },
  {
    name: "Ikram Battery Center - Ternol",
    address: "Shop#29-A Chaudhary Ayoub Market ( Bank Islami Market) G.T Road, Ternol, Islamabad",
    city: "Islamabad",
    province: "ISLAMABAD",
    contact: "0333-5189023",
  },
  {
    name: "Irfan Battery Centre - Rawalpindi",
    address: "Shop#4324-A, Main Road Daryaabad, Gowalmandi, Rawalpindi",
    city: "Rawalpindi",
    province: "PUNJAB",
    contact: "0336-0530520/0311-1519535",
  },
  {
    name: "Ittefaq Battery Agency - Rawalpindi",
    address: "Main High Court Road, Near Shell Pump, Rawalpindi",
    city: "Rawalpindi",
    province: "PUNJAB",
    contact: "0321-9114300/0345-5223418",
  },
  {
    name: "Jan Battery Center - Rawalpindi",
    address: "Main Peshawar Road, Bhatti Market Fazalabad, Rawalpindi Cantt",
    city: "Rawalpindi",
    province: "PUNJAB",
    contact: "0313-5639281",
  },
  {
    name: "Japan Tire & Battery - Haripur",
    address: "Near Shell Pump, Mohalla Tanki, G.T. Road Haripur",
    city: "Haripur",
    province: "KPK",
    contact: "0300-8325037",
  },
  {
    name: "Jawad Autos - Chakwal",
    address: "Haider Market, Main Talagang Road, Chakwal",
    city: "Chakwal",
    province: "PUNJAB",
    contact: "0336-5915572",
  },
  {
    name: "Liaqat Brothers Tyre & Battery Service - Pindi Gheb",
    address: "New Lari Adda Chowk, Pindi Gheb",
    city: "Pindi Gheb",
    province: "PUNJAB",
    contact: "0312-5424985",
  },
  {
    name: "Mehmand Traders - Haripur",
    address: "Mohalla Aslam Khan Colony, G.T Road, Haripur",
    city: "Haripur",
    province: "KPK",
    contact: "0307-2839722/0347-9540282",
  },
  {
    name: "Melody Battery.Pk - Islamabad",
    address: "Shop No.03, Block.5, Sector.G-6 Markaz,Melody Market, Islamabad",
    city: "Islamabad",
    province: "ISLAMABAD",
    contact: "",
  },
  {
    name: "Modern Battery Centre & UPS - Islamabad",
    address: "Opp. PSO Pump, Main G.T. Road, Sawan Camp, Islamabad",
    city: "Islamabad",
    province: "ISLAMABAD",
    contact: "0300-5015107",
  },
  {
    name: "Nadeem And Company - Talagang",
    address: "Near Mega Save Mart, Mianwali Road, Talagang",
    city: "Talagang",
    province: "PUNJAB",
    contact: "0300-5478650",
  },
  {
    name: "New Al-Shahbaz Battery Service - Rawalpindi",
    address: "Main Peshawar Road, Pirwadhai More, Opposite Rescue 1122, Rawalpindi",
    city: "Rawalpindi",
    province: "PUNJAB",
    contact: "",
  },
  {
    name: "New Ilyas Battery Services - Fateh Jang",
    address: "Main Khour Road, Fateh Jang",
    city: "Fateh Jang",
    province: "PUNJAB",
    contact: "0300-5312329",
  },
  {
    name: "New Kashmir Auto Battery Store - Jehlum",
    address: "Paradise Market Jehlum Cantt",
    city: "Jehlum",
    province: "PUNJAB",
    contact: "0300-5443997",
  },
  {
    name: "New Khan Battery Center & Electric Spare Parts - Wah Cantt",
    address: "Hammad Plaza, Near Barrier No.2, G.T Road, Wah Cantt",
    city: "Wah Cantt",
    province: "PUNJAB",
    contact: "03075702042",
  },
  {
    name: "New Light Battery Center - Rawalpindi",
    address: "Shop#02, Khurram Palaza, Main Haji Chowk, Sadiqabad, Rawalpindi",
    city: "Rawalpindi",
    province: "PUNJAB",
    contact: "0322-8563075",
  },
  {
    name: "New Rashid Auto Battery Store - Kotli",
    address: "New General Bus Stand, Kotli, Mirpur Azad Kashmir",
    city: "Kotli",
    province: "Azad Kashmir",
    contact: "",
  },
  {
    name: "Pak Japan Battery Centre - Islamabad",
    address: "Shop#55, Street#04, I-10/3 Auto Market Islamabad",
    city: "Islamabad",
    province: "ISLAMABAD",
    contact: "",
  },
  {
    name: "Pak Madina Battery Service - Rawalpindi",
    address: "Opposite HBL, Lethrar Road, Khan Pull Islamabad.",
    city: "Rawalpindi",
    province: "PUNJAB",
    contact: "0300-7357482/0333-7662128",
  },
  {
    name: "Prince Battery Center - Rawalpindi",
    address: "Shop#3, Awami Plaza, National Market, Chandni Chowk, Rawalpindi",
    city: "Rawalpindi",
    province: "PUNJAB",
    contact: "0317-7666507",
  },
  {
    name: "S.B Traders - Mirpur",
    address: "Al-Ghosia Market Nangi Adda, Mirpur Azad Kashmir",
    city: "Mir Pur",
    province: "Azad Kashmir",
    contact: "0342-5160008",
  },
  {
    name: "Shafqat Battery Center - Manshera",
    address: "Opposite, Hascol Petrol Pump, Shahrahe Rashim, Manshera.",
    city: "Manshera",
    province: "KPK",
    contact: "0346-4484137",
  },
  {
    name: "Shah Battery Center - Rawalpindi",
    address: "Near Bilal Masjid Main Road, Pirwadhai, Rawalpindi",
    city: "Rawalpindi",
    province: "PUNJAB",
    contact: "0305-6002942",
  },
  {
    name: "Sun Rise Battery - Jhari Kass",
    address: "",
    city: "Jhari Kass",
    province: "PUNJAB",
    contact: "",
  },
  {
    name: "Yasir Battery Service - Abbotabad",
    address: "Fawara Chowk,  Abbotabad",
    city: "Abbotabad",
    province: "KPK",
    contact: "0316-5041226",
  },
  {
    name: "Al Madina Battery Service - Mirpur Mathelo",
    address: "Shop#90, Sindhu green City, Mirpur Mathelo",
    city: "Mir Pur Methloo",
    province: "SINDH",
    contact: "0301-3832955",
  },
  {
    name: "Al Shahbaz Battery Center - Sukkur",
    address: "Dadu Chowk Near Honda Show Room Shikarpur Road, Sukkur",
    city: "Sukkur",
    province: "SINDH",
    contact: "0312-6191666",
  },
  {
    name: "Ali Traders - Ghotki",
    address: "Bypass Ghotki",
    city: "Ghotki",
    province: "SINDH",
    contact: "0302-3649914",
  },
  {
    name: "Al-Madina Battery Service - Larkana",
    address: "Al Murtaza Shoping Center, Qaim Shah Bukhari Road, Larkana",
    city: "Larkana",
    province: "SINDH",
    contact: "0333-7571286",
  },
  {
    name: "Asad Battery Centre - Dera Murad Jamali",
    address: "Near City Police Station, Quetta Road, Dera Murad Jamali",
    city: "Dera Murad Jamali",
    province: "SINDH",
    contact: "0304-8413509/0313-3663630",
  },
  {
    name: "Bolan Battery Service - Sukkur",
    address: "Race Course Road, Sukkur",
    city: "Sukkur",
    province: "SINDH",
    contact: "",
  },
  {
    name: "Classic Battery & Solar Energy - Larkana",
    address: "Near, Rehmania Masjid, karma Bagh, Larkana",
    city: "Larkana",
    province: "SINDH",
    contact: "0347-3472211",
  },
  {
    name: "Dawood Wali Autos - Sukkur",
    address: "Near Faisal Bank, Race Course Road, Sukkur",
    city: "Sukkur",
    province: "SINDH",
    contact: "0310-3375840",
  },
  {
    name: "Golden Battery Center - Sukkur",
    address: "Shop No. 567, Shikarpur Road, Sukkur",
    city: "Sukkur",
    province: "SINDH",
    contact: "0335-3144411",
  },
  {
    name: "Good Luck Electronics - Khairpur",
    address: "Phool Bagh Road, Near City Hospital, Khairpur",
    city: "Khairpur",
    province: "SINDH",
    contact: "0301-3423527/0315-3491109",
  },
  {
    name: "Hafiz Oil Traders - Sukkur",
    address: "Shop No 12, Race Course Road, Sukkur",
    city: "Sukkur",
    province: "SINDH",
    contact: "0300-2575150",
  },
  {
    name: "Haji Bashir Ahmed Solar System Electric Shop - Naushero Feroze",
    address: "Padidan Road, Naushero Feroze",
    city: "Naushero Feroze",
    province: "SINDH",
    contact: "0301-2314124/0333-7009142",
  },
  {
    name: "Indus Battery Service - Khanpur Mahar",
    address: "Near Khan Auto Garrage, Main Road Khanpur Mahar",
    city: "Khanpur Mahar",
    province: "SINDH",
    contact: "0301-3419821/0302-3155800",
  },
  {
    name: "Indus Battery Service - Larkana",
    address: "Shop#2-3-4, Al Murtaza Shoping Centre,Shah Bukhari Road, Larkana",
    city: "Larkana",
    province: "SINDH",
    contact: "",
  },
  {
    name: "Jhoolay Lal Power Solutions - Sukkur",
    address: "Race Course Road, Sukkur",
    city: "Sukkur",
    province: "SINDH",
    contact: "0305-3613014",
  },
  {
    name: "M/S Chandio Electronics Store - Dadu",
    address: "Shop#1-2 Opposite Vocational School Fish Market Road, Dadu",
    city: "Dadu",
    province: "SINDH",
    contact: "0315-9315931",
  },
  {
    name: "M/S Dawn Battery Shop - Jacobabad",
    address: "Station Road, Jacobabad",
    city: "Jacobabad",
    province: "SINDH",
    contact: "0333-7555888",
  },
  {
    name: "M/S Mumtaz Autos & Battery Service - Khairpur",
    address: "Katchery Road, Near Maryam Top, Khairpur",
    city: "Khairpur",
    province: "SINDH",
    contact: "0300-3137901/0315-3137901",
  },
  {
    name: "Madina Auto & Battery Service - Kashmore",
    address: "Railway Road, Kashmore",
    city: "Kashmore",
    province: "SINDH",
    contact: "0333-7414297/0345-8812728",
  },
  {
    name: "Madina Battery Service - Daharki",
    address: "Main G.T Road, Daharki, District Ghotki",
    city: "Deharki",
    province: "SINDH",
    contact: "0302-2344758",
  },
  {
    name: "Rehmat Auto Battery Service - Moro",
    address: "Main Road, Moro",
    city: "Moro",
    province: "SINDH",
    contact: "0311-3523468/0306-3529827",
  },
  {
    name: "Sachal Batteries Centre - Sukkur",
    address: "Near City Marriage Hall, Race Course Road, Sukkur",
    city: "Sukkur",
    province: "SINDH",
    contact: "0315-3117483/0332-1379640",
  },
  {
    name: "Sarwar Battery Service - Ranipur",
    address: "Near Taj Petrol Pump, National Highway, Ranipur",
    city: "Ranipur",
    province: "SINDH",
    contact: "0300-3137450",
  },
  {
    name: "Sheikh Adnan General, Solar and Battery Shop - Bhiria Road",
    address: "Main Shahi Bazar, Bahiria Road",
    city: "Bhiria Road",
    province: "SINDH",
    contact: "0300-2370303/0312-3268210",
  },
  {
    name: "Sindh Battery Service - Larkana",
    address: "Qaim Shah Bukhari Road, Larkana",
    city: "Larkana",
    province: "SINDH",
    contact: "0333-7576667",
  },
  {
    name: "Subhanallah Battery Service - Sukkur",
    address: "New Bus Stand, Near Super Magsi CNG Station, Sukkur",
    city: "Sukkur",
    province: "SINDH",
    contact: "0310/0302-3122994",
  },
  {
    name: "Tawakal Motors - Mehrabpur",
    address: "New Town, Theri Road, Mehrabpur",
    city: "Mehrabpur",
    province: "SINDH",
    contact: "0303-9119696/0311-3700722",
  },
  {
    name: "YJS Enterprises - Larkana",
    address: "Solar & Batteries Market, Near Midtown Mall, Pakistani Chowk Larkana",
    city: "Larkana",
    province: "SINDH",
    contact: "0333-7578814",
  },
  {
    name: "Quetta Battery & UPS Center - Chakwal",
    address: "Bhatti Market, Talagang Road, Chakwal",
    city: "Chakwal",
    province: "PUNJAB",
    contact: "0336-5786782",
  },
  {
    name: "Modern Battery Centre & UPS - Islamabad",
    address: "Opp. PSO Pump, Main G.T. Road, Sawan Camp, Islamabad",
    city: "Islamabad",
    province: "ISLAMABAD",
    contact: "0300-5015107",
  },
  {
    name: "Pak Autos & Battery Traders - Choa Syedan Shah",
    address: "Near Punjab Bank, Chakwal Road, Choa Syedan Shah",
    city: "Choa Syedan Shah",
    province: "PUNJAB",
    contact: "0332-5656933/0345-5656933",
  },
  {
    name: "Sadat Autos & Battery House - Attock",
    address: "PSO Pump Truck Adda, Attock",
    city: "Attock",
    province: "PUNJAB",
    contact: "0333-5608616",
  },
  {
    name: "Bashir & Brothers Battery & Sollar - Bannu",
    address: "Shop#03, New Cantt Market, Miranshah Road, Bannu",
    city: "Bannu",
    province: "KPK",
    contact: "0333-1919384",
  },
  {
    name: "United Auto & Battery House - Batkhela",
    address: "Near Old Dir Adda, Main Bazar, Batkhela, District Malakand",
    city: "Batkhela",
    province: "KPK",
    contact: "0348-9111366",
  },
  {
    name: "Alhafiz Oil & Battery - D. I. Khan",
    address: "Faisal Market, Near Auto Center Market, Bannu Road, D.I.Khan",
    city: "D.I.Khan",
    province: "KPK",
    contact: "0346-0220797/0346-9900098",
  },
  {
    name: "Irfan Uddin & Brothers - Landi Kotal",
    address: "G-18, Shinwari Market, Landikotal Bazar, Landikotal",
    city: "Landikotal",
    province: "KPK",
    contact: "0302-5900577",
  },
  {
    name: "Seven Star Electronics & Battery Commission Agent - Bajroh",
    address: "Main Bazar Anayat Killi, District, Bajorh",
    city: "Bajorh",
    province: "KPK",
    contact: "0300-4486839",
  },
  {
    name: "Al Hafiz Trader -  Daggar",
    address: "Ali Sher Khail, P.O Jowar, Daggar Buner.",
    city: "Buner",
    province: "KPK",
    contact: "0312-2727272/0317-8314260",
  },
  {
    name: "Saleem Electronic Battery & Solar Centre - Totalai",
    address: "Saleem Market, Near Khyber Bank, Totalai, Buner",
    city: "Totalai",
    province: "KPK",
    contact: "0342-9748127/0316-0935954",
  },
  {
    name: "Noor Autos - Kohat",
    address: "Ashiq Colony, Industrial Area Bannu Road, Kohat",
    city: "Kohat",
    province: "KPK",
    contact: "0300-91550994/0332-9786465",
  },
  {
    name: "Khalid Battery & Solar - Wari",
    address: "Near Khyber Bank, Bala Bazar, Upper Dir Wari",
    city: "Wari",
    province: "KPK",
    contact: "0321-2975550/0313-2975550/0311-8180544",
  },
  {
    name: "Sajid Battery Center - Toppi",
    address: "Swabi Road, Khan Zaman Market, Near Meezan Bank, Topi",
    city: "Toppi",
    province: "KPK",
    contact: "0315-4871718",
  },
  {
    name: "Muslim Battery Center - Peshawer",
    address: "Opp Shell Pump, Near National Kanta Ring Road, Peshawer",
    city: "Peshawer",
    province: "KPK",
    contact: "0300-5929194/0340-5036465",
  },
  {
    name: "M. Sufyan Battery and Solar System",
    address: "Karak Stand, New Adda, Bannu",
    city: "Bannu",
    province: "KPK",
    contact: "0300-5334870",
  },
  {
    name: "Sami Ullah Solar System And Battery Center - Bannu",
    address: "Kohat Road Bannu",
    city: "Bannu",
    province: "KPK",
    contact: "0336-9794004/0300-5851372",
  },
  {
    name: "Sawab Gul Battery & Solar House - Sadda",
    address: "Shaheen Market, Sadda",
    city: "Sadda",
    province: "KPK",
    contact: "0303-9012190/0302-5654286",
  },
  {
    name: "Ali & Company - Lahore",
    address: "391, Block D3, Main WAPDA Avenue, WAPDA Town, Lahore",
    city: "Lahore",
    province: "PUNJAB",
    contact: "0321-8262505",
  },
  {
    name: "Muhammad Ali Battery Service - Kusur",
    address: "Near Chowk Qadir Abad Road, Kasur",
    city: "Kasur",
    province: "PUNJAB",
    contact: "0321-6571662",
  },
  {
    name: "Haji Ikram Butt Battery Service - Lahore",
    address: "1- Nicholson Road, Qila Gujjar Singh, Lahore",
    city: "Lahore",
    province: "PUNJAB",
    contact: "0320-9448971",
  },
  {
    name: "Shahbaz Battery Service - Lahore",
    address: "Lahore Sargodha Road, Near Larri Adda Farooq Abad, Sheikhpura",
    city: "Farooq Abad",
    province: "PUNJAB",
    contact: "0322-7273824",
  },
  {
    name: "Nadeem Traders - Lahore",
    address: "Opposite Gourmet Bakery, Lahore Road, Raiwind, Lahore",
    city: "Lahore",
    province: "PUNJAB",
    contact: "0302-4561045",
  },
  {
    name: "Ahmad Battery & UPS Sale & Service - Lahore",
    address: "Fazal Market Cannal Bank Road, Thokar Niaz Baig, Lahore",
    city: "Lahore",
    province: "PUNJAB",
    contact: "0300-82029125",
  },
  {
    name: "M/S City Traders - Lahore",
    address: "Samsani Road near Pizza Hut Johar Town, Lahore",
    city: "Lahore",
    province: "PUNJAB",
    contact: "0305-3012815",
  },
  {
    name: "Arham Traders - Toba Tek Singh",
    address: "Rajana Road, Opposite Larry Adda, Toba Tek Singh",
    city: "Toba Tek Singh",
    province: "PUNJAB",
    contact: "0321-6508981",
  },
  {
    name: "Lahore Battery Service & Auto Store - Mandi Shah Jewana",
    address: "Railway Crossing, Mandi Shah Jewana",
    city: "Mandi Shah Jewana",
    province: "PUNJAB",
    contact: "0346-7374605",
  },
  {
    name: "Ahsan Battery Solar & UPS Service Centre - More Khunda",
    address: "Mirza Haroon Battery Service UPS & Solar Jaranwala Road More Khunda",
    city: "More Khunda",
    province: "PUNJAB",
    contact: "0301-4192819/0300-4902995",
  },
  {
    name: "Arslan Battery Service - Lodhran",
    address: "Daar ul Hadees Muhammadia Jalalpur More Lodhran",
    city: "Lodhran",
    province: "PUNJAB",
    contact: "0302-7346080",
  },
  {
    name: "Farooq Battery Center - Vehari",
    address: "Multan Road, Opposite Makki Masjid, Vehari",
    city: "Vehari",
    province: "PUNJAB",
    contact: "0300-7643347",
  },
  {
    name: "Khawaja Ilyas Battery Center - Jalalpur Pirwala",
    address: "Shujabad Road, Jalalpur Pirwala.",
    city: "Jalalpur Pirwala",
    province: "PUNJAB",
    contact: "0301-7763880",
  },
  {
    name: "Imran Battery Center & Solar System - Rajan Pur",
    address: "Dera Ghazi Khan Road, Rajan Pur",
    city: "Rajan Pur",
    province: "PUNJAB",
    contact: "0334-2984631",
  },
  {
    name: "Al Basit Traders - Rahim Yar Khan",
    address: "Khanpur Road, Near Punjab College, Rahim Yar Khan",
    city: "Rahmi Yar Khan",
    province: "PUNJAB",
    contact: "0300-8679922",
  },
  {
    name: "Hussnain Battery Service - Faqirwali",
    address: "Near Pathan Masjid, Highway Road, Faqirwali",
    city: "Faqirwali",
    province: "PUNJAB",
    contact: "0306-7577590/0346-8827473",
  },
  {
    name: "Ehsan Tyre & Battery Centre - Multan",
    address: "Masoom Shah Road, Opposite Alfalah Bank, Qazafi Chowk, Multan",
    city: "Multan",
    province: "PUNJAB",
    contact: "0300-7184007",
  },
  {
    name: "Khan Battery & UPS Center - Muzaffar Garh",
    address: "Jhang More, Opposite Shell Pump, Muzaffar Garh",
    city: "Muzaffar Garh",
    province: "PUNJAB",
    contact: "0300-6868708",
  },
  {
    name: "Al Makka Battery & Solar System - Muhammad Pur Dewan",
    address: "Dera Road, Muhammad Pur Dewan, Tehsil Jampur, District Rajanpur",
    city: "Muhammad Pur Dewan",
    province: "PUNJAB",
    contact: "0333-6459345",
  },
  {
    name: "Sohail Anwar & Co - Sahiwal",
    address: "Railway Road, Sahiwal",
    city: "Sahiwal",
    province: "PUNJAB",
    contact: "0300-6907423",
  },
  {
    name: "H M Marketing - Quetta",
    address: "Achakzai Market Near Satellite Town Block-3, Quetta",
    city: "Quetta",
    province: "BALOCHISTAN",
    contact: "0333-7871780",
  },
  {
    name: "M/S Mumtaz Autos & Battery Service - Khairpur ",
    address: " Katchery Road, Near Maryam Top, Khairpur",
    city: "Khairpur",
    province: "SINDH",
    contact: "0300-3137901/0315-3137901",
  },
  {
    name: "Madina Auto & Battery Service - Kashmore",
    address: "Railway Road, Kashmore",
    city: "Kashmore",
    province: "SINDH",
    contact: "0333-7414297/0345-8812728",
  },
  {
    name: "M/S Zaid Enterprises - Quetta",
    address: "Office#09, Gull's Inn Palaza, Ist Floor Angle Road, Off M.A Jinnah Road, Quetta",
    city: "Quetta",
    province: "BALOCHISTAN",
    contact: "081-2821446",
  },
  {
    name: "Akram Oil Traders - Chaman ",
    address: "Shop No.2, Qandhari, Bazar, Killa Abdullah, Chaman",
    city: "Chaman",
    province: "BALOCHISTAN",
    contact: "0345-8871701",
  },
  {
    name: "Abdul Wahid Battery Sales & Services - Hyderabad",
    address: "New Pul, Sabzi Mandi, Near Shalimar Coach Service, Hyderabad",
    city: "Hyderabad",
    province: "SINDH",
    contact: "0321-3004378",
  },
  {
    name: "Mehran Battery Sales & Services - Mirpur Khas",
    address: "Shop#1, Mashallah Market, Jarwarishakh, Mirpur Khas",
    city: "Mir Pur Khas",
    province: "SINDH",
    contact: "0310-3863564/0333-2974470",
  },
  {
    name: "Pakistan Battery Sell & Services (EXID) - Tando Adam",
    address: "Birani Road, Near Sabzi Mandi, Tando Adam, District Sanghar.",
    city: "Tando Adam",
    province: "SINDH",
    contact: "0300-3244221/0332-3244221",
  },
  {
    name: "M/S Millat Motors andTractors - Nawab Shah",
    address: "Sanghar Road, Nawab Shah",
    city: "Nawab Shah",
    province: "SINDH",
    contact: "0307-3109010/0333-3109010",
  },
  {
    name: "Jadon Autos & Battery Service - Badin",
    address: "Press Club Road, Qazia Wah Pul, Badin",
    city: "Badin",
    province: "SINDH",
    contact: "0300-3639172/0317-3141300",
  },
  {
    name: "Shahid Ali Battery Shop - Nawab Shah",
    address: "Main Qazi Ahmed Road, Near Al Haram Petrol Pump, Nawab Shah",
    city: "Nawab Shah",
    province: "SINDH",
    contact: "0300-3741344",
  },
  {
    name: "M.Nadir Khan & M.Yaseen Khan Battery Sales & Sevices - Hyderabad",
    address: "Nasrullah Market,Near Breez Fish Point, Near Paracha Autos, Hala Naka, Hyderabad",
    city: "Hyderabad",
    province: "SINDH",
    contact: "316-6695505",
  },
  {
    name: "Azaan Traders - Karachi",
    address: "Shop#5, Near Meezan Bank, Opp, Garden Police Chowki, Karachi",
    city: "Karachi",
    province: "SINDH",
    contact: "0321-2200677/0314-2221281",
  },
  {
    name: "Iman Traders - Karachi",
    address: "Ruquaiya Square Block 14, Federal B Area, Near Mehfooz Shermal, Karachi.",
    city: "Karachi",
    province: "SINDH",
    contact: "0333-3558851/0333-2159993",
  },
  {
    name: "Adnan Battery Service - Karachi",
    address: "Shop#2, Hussain Centre, Main Korangi Crossing, Near Indus Hospital, Karachi",
    city: "Karachi",
    province: "SINDH",
    contact: "0312-1280919/0323-2046599",
  },
  {
    name: "M. Salah & Sons - Karachi",
    address: "Shop # 1, Al-Fazal Terrace, Block-13, Federal B Area, Gulberg, Karachi",
    city: "Karachi",
    province: "SINDH",
    contact: "0313-2216508",
  },
  {
    name: "Ghaznavi Battery & Electric Store - Karachi",
    address: "Shop # 4, KDA Flats, Phase-2, Surjani Town, Karachi",
    city: "Karachi",
    province: "SINDH",
    contact: "0313-2810815",
  },
  {
    name: "Rahmat Auto Battery Services",
    address: "Main Road Moro",
    city: "Moro",
    province: "SINDH",
    contact: "0311-3523468/0306-3529827",
  },
  {
    name: "Ali and Company",
    address: "391 Block D3 Main WAPDA Avenue WAPDA Town Lahore",
    city: "Lahore",
    province: "PUNJAB",
    contact: "0321-8262505",
  },
  {
    name: "Jadon Autos & Battery Service - Badin",
    address: "Press Club Road, Qazia Wah Pul, Badin",
    city: "Badin",
    province: "SINDH",
    contact: "0300-3639172/0317-3141300",
  },
  {
    name: "Shahid Ali Battery Shop - Nawab Shah",
    address: "Main Qazi Ahmed Road, Near Al Haram Petrol Pump, Nawab Shah",
    city: "Nawab Shah",
    province: "SINDH",
    contact: "0300-3741344",
  },
  {
    name: "M.Nadir Khan & M.Yaseen Khan Battery Sales & Sevices - Hyderabad",
    address: "Nasrullah Market,Near Breez Fish Point, Near Paracha Autos, Hala Naka, Hyderabad",
    city: "Hyderabad",
    province: "SINDH",
    contact: "316-6695505",
  },
  {
    name: "Azaan Traders - Karachi",
    address: "Shop#5, Near Meezan Bank, Opp, Garden Police Chowki, Karachi",
    city: "Karachi",
    province: "SINDH",
    contact: "0321-2200677/0314-2221281",
  },
  {
    name: "Iman Traders - Karachi",
    address: "Ruquaiya Square Block 14, Federal B Area, Near Mehfooz Shermal, Karachi.",
    city: "Karachi",
    province: "SINDH",
    contact: "0333-3558851/0333-2159993",
  },
  {
    name: "Adnan Battery Service - Karachi",
    address: "Korangi Nasir Jump, Near Mughal-e-Azam Banquet, Karachi",
    city: "Karachi",
    province: "SINDH",
    contact: "0312-1280919/0323-2046599",
  },
  {
    name: "M. Salah & Sons - Karachi",
    address: "Shop#16, Sector 1/A, Metro Cinema Road, Korangi Town, Karachi",
    city: "Karachi",
    province: "SINDH",
    contact: "0314-2345532/0333-2493714",
  },
  {
    name: "Ghaznavi Battery & Electric Store - Karachi",
    address: "Shop No:4, Main Jinnah Square, Opposite Karachi Ice Cream, Malir Karach",
    city: "Karachi",
    province: "SINDH",
    contact: "0317-1287855",
  },
  {
    name: "Rahmat Auto Battery Services",
    address: "Main Road Moro Tahsil Moro Sindh Disst Naushahro Feroze",
    city: "Moro",
    province: "SINDH",
    contact: "0306-3529827 / 0311-3523468 / 0323-3900155",
  },
  {
    name: "Ali and Company",
    address: "391-Sector D/3, Wapda Town, Lahore",
    city: "Lahore",
    province: "PUNJAB",
    contact: "0321-8262405 0337-4633900",
  },
];

document.addEventListener("DOMContentLoaded", () => {
  const searchInput = document.getElementById("dealerSearch");
  const provinceSelect = document.getElementById("provinceFilter");
  const dealerList = document.getElementById("dealerList");
  const dealerCount = document.getElementById("dealerCount");
  const dealerCountDisplay = document.getElementById("dealerCountDisplay");

  function renderDealers(data) {
    dealerList.innerHTML = "";
    dealerCount.innerText = data.length;
    if (dealerCountDisplay) dealerCountDisplay.innerText = data.length;

    if (data.length === 0) {
      dealerList.innerHTML = `
                <div class="p-10 text-center border-2 border-dashed border-gray-100">
                    <p class="text-gray-400 font-black uppercase text-xs tracking-widest">No dealers found in this region</p>
                </div>`;
      return;
    }

    data.forEach((dealer) => {
      const card = document.createElement("div");
      card.className = "dealer-card bg-white border-2 border-gray-200 p-5 rounded-lg hover:border-[#c00d1e] hover:shadow-md transition-all group cursor-pointer";
      card.innerHTML = `
                <div class="flex justify-between items-start mb-3">
                    <div class="flex-1">
                        <h4 class="text-zinc-900 font-bold uppercase tracking-wide text-sm mb-2 group-hover:text-[#c00d1e] transition-colors">${dealer.name}</h4>
                        <p class="text-gray-600 text-xs font-medium leading-relaxed">${dealer.address}</p>
                    </div>
                    <span class="text-xs bg-gray-100 text-[#c00d1e] px-3 py-1 rounded-full font-bold uppercase ml-2 whitespace-nowrap">${dealer.province}</span>
                </div>
                <div class="flex items-center gap-3 pt-3 border-t border-gray-100">
                    <a href="tel:${dealer.contact}" class="text-zinc-900 text-xs font-bold uppercase tracking-wide hover:text-[#c00d1e] transition-colors flex items-center gap-1">
                        <i class="fa-solid fa-phone text-[10px]"></i>
                        ${dealer.contact}
                    </a>
                    <span class="text-gray-300">|</span>
                    <button class="text-[#c00d1e] text-xs font-semibold uppercase tracking-wide hover:underline">Get Directions</button>
                </div>
            `;
      dealerList.appendChild(card);

      // Add click handler to update map and scroll
      card.addEventListener("click", () => {
        updateMapLocation(dealer.address);
        scrollToSearchBar();
      });
    });
  }

  function filterDealers() {
    const term = searchInput.value.toLowerCase();
    const prov = provinceSelect.value;
    const provNorm = (prov || "").toLowerCase();

    const filtered = dealers.filter((d) => {
      const matchesSearch = d.name.toLowerCase().includes(term) || d.address.toLowerCase().includes(term) || d.city.toLowerCase().includes(term) || d.province.toLowerCase().includes(term);
      const dProv = (d.province || "").toLowerCase();
      const matchesProv = prov === "All" || dProv === provNorm || (provNorm === "gilgit baltistan" && dProv.includes("gilgit"));
      return matchesSearch && matchesProv;
    });

    renderDealers(filtered);
  }

  searchInput.addEventListener("input", filterDealers);
  provinceSelect.addEventListener("change", filterDealers);

  // Clear button and suggestions
  const dealerClear = document.getElementById("dealerClear");
  const suggestionsBox = document.getElementById("dealer-suggestions");

  function updateSuggestions(term) {
    term = (term || "").toLowerCase().trim();
    if (!term) {
      suggestionsBox.classList.add("hidden");
      return;
    }

    const prov = provinceSelect.value;
    const provNorm = (prov || "").toLowerCase();

    const matches = dealers
      .filter((d) => {
        const matchesSearch = d.name.toLowerCase().includes(term) || d.address.toLowerCase().includes(term) || d.city.toLowerCase().includes(term) || d.province.toLowerCase().includes(term);
        const dProv = (d.province || "").toLowerCase();
        const matchesProv = prov === "All" || dProv === provNorm || (provNorm === "gilgit baltistan" && dProv.includes("gilgit"));
        return matchesSearch && matchesProv;
      })
      .slice(0, 8);

    if (matches.length === 0) {
      suggestionsBox.innerHTML = `<div class="p-3 text-gray-500 text-sm">No suggestions</div>`;
      suggestionsBox.classList.remove("hidden");
      return;
    }

    suggestionsBox.innerHTML = matches
      .map(
        (m) =>
          `<button type="button" class="w-full text-left px-4 py-2 hover:bg-gray-100 suggestion-item" data-value="${escapeHtml(
            m.name,
          )}"><div class="text-sm font-bold">${escapeHtml(m.name)}</div><div class="text-xs text-gray-500">${escapeHtml(m.city)} • ${escapeHtml(m.province)}</div></button>`,
      )
      .join("");

    suggestionsBox.classList.remove("hidden");
  }

  function escapeHtml(str) {
    return String(str).replace(/[&"'<>]/g, (s) => ({ "&": "&amp;", '"': "&quot;", "'": "&#39;", "<": "&lt;", ">": "&gt;" })[s]);
  }

  // Show/hide clear button
  function toggleClear() {
    if ((searchInput.value || "").trim()) {
      dealerClear.classList.remove("hidden");
    } else {
      dealerClear.classList.add("hidden");
    }
  }

  // Wire input to suggestions + clear button
  searchInput.addEventListener("input", function (e) {
    toggleClear();
    updateSuggestions(this.value);
  });

  dealerClear.addEventListener("click", function (e) {
    e.preventDefault();
    searchInput.value = "";
    toggleClear();
    suggestionsBox.classList.add("hidden");
    filterDealers();
    searchInput.focus();
  });

  // Delegate suggestion clicks
  suggestionsBox.addEventListener("click", function (e) {
    const btn = e.target.closest(".suggestion-item");
    if (!btn) return;
    const val = btn.getAttribute("data-value");
    if (val) {
      searchInput.value = val;
      toggleClear();
      suggestionsBox.classList.add("hidden");
      filterDealers();
    }
  });

  // Hide suggestions when clicking outside
  document.addEventListener("click", function (e) {
    if (!e.target.closest("#dealer-suggestions") && !e.target.closest("#dealerSearch")) {
      suggestionsBox.classList.add("hidden");
    }
  });

  // Update map location function
  function updateMapLocation(address) {
    const mapIframe = document.getElementById("dealerMap");
    const encodedAddress = encodeURIComponent(address);
    mapIframe.src = `https://maps.google.com/maps?q=${encodedAddress}&t=&z=13&ie=UTF8&iwloc=&output=embed`;
  }

  // Scroll to search bar function
  function scrollToSearchBar() {
    const searchSection = document.querySelector(".max-w-7xl");
    if (searchSection) {
      searchSection.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  }

  // Initial load
  renderDealers(dealers);
});
